---
- name: APT update & upgrade only if updates exist
  hosts: all
  become: yes

  tasks:

    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Check how many packages would be upgraded
      ansible.builtin.command: apt-get --just-print upgrade
      register: upgrade_check
      changed_when: false

    - name: Extract number of upgradeable packages
      ansible.builtin.set_fact:
        upgrade_count: "{{ upgrade_check.stdout | regex_findall('Inst ') | length }}"

    - name: Debug – show number of upgradeable packages
      ansible.builtin.debug:
        msg: "Es sind {{ upgrade_count }} Pakete upgradebar."

    - name: Upgrade durchführen, wenn Pakete vorhanden sind
      ansible.builtin.apt:
        upgrade: yes
      when: upgrade_count | int > 0
